version: '3'
services:
  db:
   image: mysql:5.6
   restart: always
   volumes:
     - ./db_data/:/docker-entrypoint-initdb.d
   environment:
     MYSQL_ROOT_PASSWORD: 'root'
     MYSQL_DATABASE: 'products'
     MYSQL_USER: 'user'
     MYSQL_PASSWORD: 'root'
   ports:
     - '3306:3306'
   expose:
     - '3306'
     
volumes:
   product-db: